### ISSUE TITLE
Postinstall scriptlets of ['fstools', 'eudev'] have failed

### ISSUE THREAD

**Issue by outbackdingo** [tano-systems/meta-tanowrt#9]
seems encountering a bit of a failure

ERROR: tanowrt-image-full-1.0-tano0.6 do_rootfs: Postinstall scriptlets of ['fstools', 'eudev'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

**Comment by namedun** [comment]
It looks like you are using Ubuntu and have not made the correct configuration of the default system shell as described in the documentation (see https://tano-systems.github.io/meta-tanowrt/build.html#install-required-packages).

```
sudo dpkg-reconfigure dash
```

Select **No** when it asks you to install dash as `/bin/sh`.

**Comment by outbackdingo** [comment]
Its not ubuntu, its fedora and that uses bash... dig deeper....

**Comment by namedun** [comment]
Sorry, under Fedora we have no way to check at the moment. I can recommend try to build in a Docker environment (https://tano-systems.github.io/meta-tanowrt/extra/build-docker.html).

**Comment by outbackdingo** [comment]
That doesnt appear to work either

docker run --rm -it -v ~/tanowrt:/tanowrt ubuntu:tanowrt-build /bin/bash
***@***.***:~$ cd /tanowrt
***@***.***:/tanowrt$ kas build kas/targets/qemux86-64-screen.yml
2023-02-12 12:41:43 - INFO     - kas 3.1 started
2023-02-12 12:41:43 - INFO     - /tanowrt/kas/targets$ git rev-parse
--show-toplevel
2023-02-12 12:41:43 - INFO     - /tanowrt/kas/targets$ hg root
2023-02-12 12:41:43 - INFO     - /tanowrt/kas/targets$ git rev-parse
--show-toplevel
2023-02-12 12:41:43 - INFO     - /tanowrt/kas/targets$ hg root
2023-02-12 12:41:43 - ERROR    - [Errno 2] No such file or directory:
'/tanowrt/kas/targets/kas/tanowrt-core.yml'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kas/kas.py", line 165, in
main
    sys.exit(kas(sys.argv[1:]))
  File "/usr/local/lib/python3.8/dist-packages/kas/kas.py", line 154, in kas
    plugin.run(args)
  File "/usr/local/lib/python3.8/dist-packages/kas/plugins/build.py", line
90, in run
    macro.run(ctx, args.skip)
  File "/usr/local/lib/python3.8/dist-packages/kas/libcmds.py", line 99, in
run
    command.execute(ctx)
  File "/usr/local/lib/python3.8/dist-packages/kas/libcmds.py", line 349,
in execute
    ctx.missing_repo_names = ctx.config.find_missing_repos()
  File "/usr/local/lib/python3.8/dist-packages/kas/config.py", line 75, in
find_missing_repos
    self.handler.get_config(repos=repo_paths)
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
266, in get_config
    cfgs, reps = _internal_include_handler(configfile,
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
198, in _internal_include_handler
    (cfg, rep) = _internal_include_handler(includefile,
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
172, in _internal_include_handler
    current_config = load_config(filename)
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
63, in load_config
    with open(filename, 'rb') as fds:
FileNotFoundError: [Errno 2] No such file or directory:
'/tanowrt/kas/targets/kas/tanowrt-core.yml'
***@***.***:/tanowrt$

**Comment by namedun** [comment]
Looks like you mount invalid directory of the meta-tanowrt repository into dockers `/tanowrt` directory. Check `/tanowrt` directory contents in docker:
```
build@108a8bcb14c2:~$ 
build@108a8bcb14c2:~$ cd /tanowrt/
build@108a8bcb14c2:/tanowrt$ ls
bitbake  docs  LICENSE     meta-arm    meta-openembedded  meta-swi         meta-swupdate  meta-tanowrt-hsl-atmel   meta-tanowrt-hsl-brcm   meta-tanowrt-hsl-nxp       meta-tanowrt-hsl-swi         meta-tanowrt-hsl-ti   meta-ti            README.md
build    kas   local.conf  meta-atmel  meta-qt5           meta-swi-extras  meta-tanowrt   meta-tanowrt-hsl-baikal  meta-tanowrt-hsl-intel  meta-tanowrt-hsl-rockchip  meta-tanowrt-hsl-swi-extras  meta-tanowrt-staging  openembedded-core  scripts
```

And recheck your path on the host system to meta-tanowrt repository in command:
```
docker run --rm -it -v ~/tanowrt:/tanowrt ubuntu:tanowrt-build /bin/bash
```

You have cloned meta-tanowrt repository into `~/tanowrt`?

**Comment by outbackdingo** [comment]
As I said i followed the instructions implicitly, it doesnt appear to work

git clone --recursive https://github.com/tano-systems/meta-tanowrt tanowrt
Cloning into 'tanowrt'...
remote: Enumerating objects: 34109, done.
remote: Counting objects: 100% (7029/7029), done.
remote: Compressing objects: 100% (2714/2714), done.
remote: Total 34109 (delta 3527), reused 6988 (delta 3509), pack-reused
27080
Receiving objects: 100% (34109/34109), 39.22 MiB | 3.68 MiB/s, done.
Resolving deltas: 100% (19494/19494), done.
Submodule 'bitbake' (https://github.com/openembedded/bitbake.git)
registered for path 'bitbake'
Cloning into '/home/dingo/tanowrt/bitbake'...
remote: Enumerating objects: 62198, done.
remote: Counting objects: 100% (875/875), done.
remote: Compressing objects: 100% (340/340), done.
remote: Total 62198 (delta 637), reused 750 (delta 533), pack-reused 61323

Receiving objects: 100% (62198/62198), 22.23 MiB | 3.78 MiB/s, done.
Resolving deltas: 100% (44249/44249), done.
Submodule path 'bitbake': checked out
'72a3afd99e8b785cb2a2f687e71a58e08cdd9c74'
❯ cd ~/tanowrt
❯ cd .ci
❯ docker build -t ubuntu:tanowrt-build \
                                       --build-arg host_uid=$(id -u) \
                                       --build-arg host_gid=$(id -g) \
                                       -f Dockerfile .
STEP 1/20: FROM ubuntu:20.04
STEP 2/20: ARG timezone=Europe/Moscow
--> Using cache
19838d5e706ef6e4cc64be8baddb893ef55f7c306c658f66d3a6ce8236f2dc96
--> 19838d5e706
STEP 3/20: ENV TZ=${timezone}
--> Using cache
15062c57e644f55a19b7b5b1b2f4d19ea39ad402056fcd343e396fa610332623
--> 15062c57e64
STEP 4/20: RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >
/etc/timezone
--> Using cache
256fc97596fbca052db5f1e2afc097d6ee40dd9584650c587e6b9325340da457
--> 256fc97596f
STEP 5/20: RUN apt-get update && apt-get install --no-install-recommends -y
    gawk wget git-core diffstat unzip texinfo gcc-multilib
build-essential chrpath socat cpio     python python-jinja2
python-setuptools     python3 python3-pip python3-pexpect     xz-utils
debianutils iputils-ping locales openssh-client file tmux     liblz4-tool
zstd
--> Using cache
9ae93321f3e4ec49f30625590107601892f29891eb3a9cb00bc34229215e2c9c
--> 9ae93321f3e
STEP 6/20: RUN pip3 install kas==3.1.0
--> Using cache
9ad11f5ad5361f69c1af3ad22ebbf6c5c20ecd5c280bb74781bb5e4c6dfbd71c
--> 9ad11f5ad53
STEP 7/20: RUN rm /bin/sh && ln -s bash /bin/sh
--> Using cache
b0d5426ea82eedd9046c004ceb4a15e9cbe1b527aced79898707cd7e3752fd6b
--> b0d5426ea82
STEP 8/20: RUN locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8
  LANG=en_US.UTF-8
--> Using cache
e162c2531e3ab63d7d90d3f05a938dd1bf0eb8578061db9f766e16863be63eaf
--> e162c2531e3
STEP 9/20: ENV LANG en_US.UTF-8
--> Using cache
2b23e56b25a38cef4e254ab9bf572516b81e86fd0d59f0405c8f0b842254c562
--> 2b23e56b25a
STEP 10/20: ENV LC_ALL en_US.UTF-8
--> Using cache
324d2320a8b0c6eb290a3aab8004f36e34881f1e4f56a3663f8e49c55281b5a6
--> 324d2320a8b
STEP 11/20: ARG host_uid=1000
--> Using cache
efb8126837bb145039ba8ede873ba5477d56bea5b915bbc2f10cf59caf08b94c
--> efb8126837b
STEP 12/20: ARG host_gid=1000
--> Using cache
5c9cfbd550e0ae7eb3282cf88bb57ba0232bc3bfeea42592ba173a7b4591de9c
--> 5c9cfbd550e
STEP 13/20: ARG username=build
--> Using cache
d9074071c45972be52459e7ab47420b1eabcc2b1e98c88415d01aa8a70bb3be2
--> d9074071c45
STEP 14/20: ARG project=tanowrt
--> Using cache
9bbd197e7a862ca900b58dc12fae3669f7b1cbe1544fbf5fe11ed0edbf75a29f
--> 9bbd197e7a8
STEP 15/20: ENV USERNAME ${username}
--> Using cache
68f5b04bf57ecaf28f0d0b854bbf947671d271cd7094c86cb3f2a4e6456b335f
--> 68f5b04bf57
STEP 16/20: ENV PROJECT ${project}
--> Using cache
f609c01e7264ca97b9e0ecf2ba145b3d40e89b01736c11564f46043a32924c7e
--> f609c01e726
STEP 17/20: RUN groupadd -g $host_gid $USERNAME &&     useradd -g $host_gid
-m -s /bin/bash -u $host_uid $USERNAME
--> Using cache
d06892b87b9f68f7e4ce2f40f87954a9a9ed4d8d7b3307aa4561fc40486f05de
--> d06892b87b9
STEP 18/20: USER $USERNAME
--> Using cache
7da8ef5eb88b6c31ccc7d3228dca80a7112c70120ff5304d82e1c89b7cb50e43
--> 7da8ef5eb88
STEP 19/20: WORKDIR /home/${USERNAME}
--> Using cache
46efd6443685e4e9ce4de55aa496bb64950fdec0a449b58125da06db15701296
--> 46efd644368
STEP 20/20: CMD ["/bin/bash", "--login"]
--> Using cache
3707ffcfc2c741dc6aa66a36be26852a5be98bf2cb4eac968cd89b63a754459a
COMMIT ubuntu:tanowrt-build
--> 3707ffcfc2c
Successfully tagged localhost/ubuntu:tanowrt-build
3707ffcfc2c741dc6aa66a36be26852a5be98bf2cb4eac968cd89b63a754459a
❯ cd ..
❯ docker run --rm -it -v ~/tanowrt:/tanowrt ubuntu:tanowrt-build /bin/bash
***@***.***:~$ cd /tanowrt/
***@***.***:/tanowrt$ ls
bitbake  docs  LICENSE       meta-tanowrt-hsl-atmel   meta-tanowrt-hsl-brcm
  meta-tanowrt-hsl-nxp       meta-tanowrt-hsl-swi  README.md
build    kas   meta-tanowrt  meta-tanowrt-hsl-baikal
 meta-tanowrt-hsl-intel  meta-tanowrt-hsl-rockchip  meta-tanowrt-hsl-ti
scripts
***@***.***:/tanowrt$ kas build kas/targets/qemux86-64-screen.yml
2023-02-12 16:14:14 - INFO     - kas 3.1 started
2023-02-12 16:14:14 - INFO     - /tanowrt/kas/targets$ git rev-parse
--show-toplevel
2023-02-12 16:14:14 - INFO     - /tanowrt/kas/targets$ hg root
2023-02-12 16:14:14 - INFO     - /tanowrt/kas/targets$ git rev-parse
--show-toplevel
2023-02-12 16:14:14 - INFO     - /tanowrt/kas/targets$ hg root
2023-02-12 16:14:14 - ERROR    - [Errno 2] No such file or directory:
'/tanowrt/kas/targets/kas/tanowrt-core.yml'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/kas/kas.py", line 165, in
main
    sys.exit(kas(sys.argv[1:]))
  File "/usr/local/lib/python3.8/dist-packages/kas/kas.py", line 154, in kas
    plugin.run(args)
  File "/usr/local/lib/python3.8/dist-packages/kas/plugins/build.py", line
90, in run
    macro.run(ctx, args.skip)
  File "/usr/local/lib/python3.8/dist-packages/kas/libcmds.py", line 99, in
run
    command.execute(ctx)
  File "/usr/local/lib/python3.8/dist-packages/kas/libcmds.py", line 349,
in execute
    ctx.missing_repo_names = ctx.config.find_missing_repos()
  File "/usr/local/lib/python3.8/dist-packages/kas/config.py", line 75, in
find_missing_repos
    self.handler.get_config(repos=repo_paths)
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
266, in get_config
    cfgs, reps = _internal_include_handler(configfile,
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
198, in _internal_include_handler
    (cfg, rep) = _internal_include_handler(includefile,
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
172, in _internal_include_handler
    current_config = load_config(filename)
  File "/usr/local/lib/python3.8/dist-packages/kas/includehandler.py", line
63, in load_config
    with open(filename, 'rb') as fds:
FileNotFoundError: [Errno 2] No such file or directory:
'/tanowrt/kas/targets/kas/tanowrt-core.yml'
***@***.***:/tanowrt$

**Comment by outbackdingo** [comment]
this must be something fedora / docker specific even... i just tried on a freinds ubuntu, and seems its working... we will see if it builds

**Comment by namedun** [comment]
Okay, I'll reopen this issue. I will try to see what is going on Fedora when I have time. Can you please tell me more exactly what version of distribution you have, architecture, etc?

**Comment by outbackdingo** [comment]
fedora 33, x86_64... generally runs zsh... but switched to bash
❯ docker version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 22:01:27 2022
OS/Arch:      linux/amd64
